### ISSUE TITLE
add support for WD Large model

### ISSUE THREAD

**Issue by DEX-1101** [corkborg/wd14-tagger-standalone#15]
https://huggingface.co/SmilingWolf/wd-vit-large-tagger-v3

**Comment by corkborg** [comment]
@DEX-1101 
Thanks for letting me know!

I think this model is compatible and will work as is except for the download part.

What do you think?

**Comment by DEX-1101** [comment]
i just test it and it's working, a bit slower than normal one maybe due the large model but that's fine.
