### ISSUE TITLE
[Feature Request] Add Z3D-E621-Convnext

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [corkborg/wd14-tagger-standalone#18]
https://huggingface.co/toynya/Z3D-E621-Convnext
This model is trained based on e621 and is one of the models that outputs detailed tags. I would be very happy to see this supported.

**Comment by corkborg** [comment]
Hi!

The z3d-e621 model seemed to be compatible and supportable.

example: #19 
```
python run.py --file image.jpg --model z3d-e621-convnext-toynya
python run.py --file image.jpg --model z3d-e621-convnext-silveroxides
```

https://huggingface.co/toynya/Z3D-E621-Convnext
https://huggingface.co/silveroxides/Z3D-E621-Convnext

There doesn't seem to be much information about Z3D-E621-Convnext on the Internet, but who are they? 🤔

**Comment by corkborg** [comment]
@Bocchi-Chan2023 
Hi!

The z3d-e621 model seemed to be compatible and supportable.

example: https://github.com/corkborg/wd14-tagger-standalone/pull/19

python run.py --file image.jpg --model z3d-e621-convnext-toynya
python run.py --file image.jpg --model z3d-e621-convnext-silveroxides
https://huggingface.co/toynya/Z3D-E621-Convnext
https://huggingface.co/silveroxides/Z3D-E621-Convnext

There doesn't seem to be much information about Z3D-E621-Convnext on the Internet, but who are they? 🤔
