### ISSUE TITLE
add more options

### ISSUE THREAD

**Issue by DEX-1101** [corkborg/wd14-tagger-standalone#8]
Hi,
it is possible to add more option to recursive all subdir for the folder image and removing undesired tags?, would be good if can, thank you for reading this.

**Comment by corkborg** [comment]
@DEX-1101 
Hi!

Just to confirm, are we talking about the recursive option and the option to ignore tags?
Or are you talking about removing undesired tags from a caption file that has already been predicted?

**Comment by DEX-1101** [comment]
yes, recursive option and ingnore tags from caption file when predicting, so it won't included, similar option like on kohya script (here)[https://github.com/kohya-ss/sd-scripts/blob/main/finetune/tag_images_by_wd14_tagger.py}

**Comment by corkborg** [comment]
I think I have implemented the recursive option.

undesired tags option may take a little longer as there are a few things to consider.

**Comment by DEX-1101** [comment]
thank you sir, have a nice day

**Comment by corkborg** [comment]
Added option to remove undesired tags.

```
python3 run.py --exclude-tag "aaa,bb b,ccc"
```

I'm not sure if I'm handling the discrepancy between the nai style tags and the danbooru style tags correctly.

**Comment by DEX-1101** [comment]
thanks, will try it
